New fields added
perryfaro/sepa pull request #3
Opened 2017-08-30 22:48 UTC by miquelbotanch

All new fields are optional

Group Header:
NifSuffix Company Id to identify Company (Mandatory at Spain)
Payment: 
CreditorAddress
CreditorAddress (2nd line)
CreditorCountry
IsSepa (for sepa and non sepa payments, they can be mixed in the xml)
CtgyPurp to identify if the payment is a salary or supplier payment (all available options are in comments) the good part is that using CtgyPurp at payment level allows you to put any kind of payment together in the same XML, if it's done on the header, you've to create an XML per purpose.

2017-10-22 21:32 UTC, perryfaro requested changes

2017-10-22 21:32 UTC, perryfaro commented on docs/install.rst
> +    composer require aculvi/sepa
Can you change this back to perryfaro instead of aculvi?

2017-10-22 21:32 UTC, perryfaro commented on composer.json
> +            "name": "Alan Culvi"
Can you change this back to perryfaro instead of aculvi?

2017-10-22 21:32 UTC, perryfaro commented on composer.json
> +    "name": "aculvi/sepa",
Can you change this back to perryfaro instead of aculvi?

2021-01-06 00:03 UTC, closed without merging

2022-12-22 01:21 UTC, miquelbotanch commented
Sorry but, could you tell me why my PR has not been accepted  ?
I would like to continue using your repository, but unfortunately in Spain we're forced to use that fields, so I need to add it. in case that in other countries is not necessary, it simply doesn't affect the result XML.